### ISSUE TITLE
Meta-issue: merge SHAP Community Fork

### ISSUE THREAD

**Issue by connortann** [shap/shap#2944]
This is a meta-issue to track progress towards merging the [SHAP Community Fork](https://github.com/dsgibbons/shap) into this upstream project.

See discussion: https://github.com/slundberg/shap/discussions/2942

TODO:

- [x] Fix failing CodeQL checks: https://github.com/dsgibbons/shap/pull/104
- [x] Prepare branch that removes fork-specific changes: https://github.com/dsgibbons/shap/pull/103
- [x] Complete main outstanding PRs in dsgibbons/shap:
   - [x] https://github.com/dsgibbons/shap/pull/102
   - [x] https://github.com/dsgibbons/shap/pull/101
   - [x] https://github.com/dsgibbons/shap/pull/99
   - [x] https://github.com/dsgibbons/shap/pull/97
   - [x] https://github.com/dsgibbons/shap/pull/105
- [x] PR to merge from fork into upstream: https://github.com/slundberg/shap/pull/2943
  - [x] In the description, link all relevant issues in upstream repository that will be closed
      - Done a first-pass, but there may be more
  - [x] Reviews from SHAP Community Fork maintainers
  - [x] Merge without squashing
