### ISSUE TITLE
Meta-issue: preparing for a release

### ISSUE THREAD

**Issue by connortann** [shap/shap#2979]
## Overview

It has been over a year since the last release. A number of bugs and deprecations have been implemented on the community-led [SHAP Community Fork](https://github.com/dsgibbons/shap), which was recently merged in #2943. It would be great to make these fixes available on PyPI. This meta-issue tracks progress towards making a release.

## Context

So far the repository has been administered by @slundberg. Now that we have a small but growing pool of maintainers, we could take this opportunity to review the release process to ensure it is documented, repeatable and appropriately automated.

## TODO

(Maintainers: feel free to edit)

### Critical path

- [x] Define steps to make a release
- [x] Review setup of PyPI secrets & permissions
- [x] Update CHANGELOG.md
  - #2990
- [x] Update build action to run tests against wheel
  - #2995
  - #3015
- [x] Fix failing tests on built wheel
  - #3012
  - #3030 
  - #3032
  - #3020
  - #3029
  - #3048
- [x] Bump version in `__init__.py` and `CHANGELOG.md`
   - #3058 
- [x] Dry-run release with https://test.pypi.org/
  - #3014
- [x] Fix failing build with numpy `1.24`
  - #3063
  - #3064
- [x] Publish release `v0.42.0` to pypi
- [x] Publish release `v0.42.0` to conda feedstock
   - https://github.com/conda-forge/shap-feedstock/pull/57

### Longer term

- [ ] Agree a release strategy
   - [ ] Document somewhere (in a CONTRIBUTING.md ?)
   - [ ] Define who can trigger a release, and when
- [x] Migration repo to `SHAP` GH Org (Pending discussion)
- [x] Review packaging configuration
  - #3022
  - #3019
- [x] Review the GH Actions workflow for publishing to PyPI
   - [x] Consider running unit tests from the _built_ packages, not a local install
   - [X] Consider updating build logic to a modern [PEP-517](https://peps.python.org/pep-0517/)-compliant setup. EDIT: Build dependencies are already defined in pyproject.toml and picked up by cibuildwheel, no change needed.
   - [x] Deploy to TestPyPi on CI when wheels are built

@dsgibbons @thatlittleboy @slundberg  what do you think?

**Comment by thatlittleboy** [comment]
On release strategy, I think we can keep it flexible initially. If one of us thinks it's time for a release, we can raise it in our (private) team discussions, once we have migrated to the `shap` organisation.

For sure we can make steps towards a release now, then I suggest we revisit this decision again once most of the items here are ticked off.

I'm slightly leaning towards migrating orgs before the release, just for easier communication and alignment, if nothing else. but obviously that depends on how long it takes to initiate and complete the migration.

**Comment by thatlittleboy** [comment]
@slundberg Any updates/ETA on the transfer of the project to the `shap` organization?

**Comment by desilinguist** [comment]
Just as one data point, we would be really grateful for an earlier release since one of our [projects](https://github.com/EducationalTestingService/rsmtool) is reliant heavily on `shap`. However, we would totally understand if you all want to do the migration before the release. Thank you again for contributing your time and energy to rejuvenate this helpful project! 🙏🏽

**Comment by christopherbunn** [comment]
I'll also +1 the above comment and mention that our library [EvalML](https://www.github.com/alteryx/evalml) also makes heavy use of shap. A number of issues that are currently merged to main but not released yet would move forward a good number of initiatives/bug fixes we have planned. We definitely appreciate the new maintainers for picking up this project up again!

**Comment by dsgibbons** [comment]
@connortann I wonder if we release 0.42 sooner rather than later. It may not be perfect but I think implementing all of the above may take a while.

**Comment by jklaise** [comment]
At the risk of being slightly off-topic (perhaps something for 0.43 since it would indeed be preferable to get 0.42 out quickly) is the fact that the the sdist available on PyPI doesn't include the cuda files under `shap/cext`, therefore `GPUTreeExplainer` cannot work at all. This is likely to be a packaging issue, but I haven't been able to replicate it locally (and it's challenging because packaging instructions are not documented). Relevant issue: https://github.com/slundberg/shap/issues/1834

**Comment by connortann** [comment]
> @connortann I wonder if we release 0.42 sooner rather than later. It may not be perfect but I think implementing all of the above may take a while.

@dsgibbons I agree to an extent. However, as a minimum I think we absolutely must test the packing and release process before triggering a public release. Given the huge number of downstream users of this package, a broken release could be pretty catastrophic!

I think this next release is particularly risky: this may be the first time that someone other than the original creator makes a release of shap, and AFAIK we've had slim to zero handover.

**Comment by connortann** [comment]
I updated the checklist to split out what tasks we could defer to after a next release.

**Comment by dsgibbons** [comment]
> I think this next release is particularly risky: this may be the first time that someone other than the original creator makes a release of shap, and AFAIK we've had slim to zero handover.

I'll get in touch with Scott and see if we can get access to PyPI secrets and previous release steps.

**Comment by PrimozGodec** [comment]
@desilinguist, I think this repository already has PyPI secrets (that should be enough for release) stored in the secrets setting (named PYPI_TOKEN). It is used here to publish wheels: https://github.com/slundberg/shap/blob/f77a5ae5c6fefa9a353cdd5422e05b4e565904a3/.github/workflows/build_wheels.yml#LL89C52-L89C52.

Anyway, it is good for you as a maintainer to get access as an admin at PyPI in case anything gets wrong. 

Currently, the release steps are the following (it would be nice to put instructions in some wiki):
1. Make a new tag (e.g. 0.42) and push it to this repository
2. Initiate the release on GitHub (through an interface on the right-hand side in the Releases section)
3. The latter will trigger the https://github.com/slundberg/shap/blob/master/.github/workflows/build_wheels.yml action to make and publish wheels on PyPI.

Before the release, we should run this action to see what wheels it builds. I can try to to this later.

**Comment by PrimozGodec** [comment]
So as promised, I tested wheel building and updated the workflow accordingly: https://github.com/slundberg/shap/pull/2995.
The updated workflow doesn't run in the PR since it only runs on new releases (when manually triggered). You can see the resulting builds (and wheels) here: https://github.com/PrimozGodec/shap/actions/runs/5287884834.

When PR is merged, release can be made according to the instructions in the previous comment.

**Comment by jklaise** [comment]
> At the risk of being slightly off-topic (perhaps something for 0.43 since it would indeed be preferable to get 0.42 out quickly) is the fact that the the sdist available on PyPI doesn't include the cuda files under `shap/cext`, therefore `GPUTreeExplainer` cannot work at all. This is likely to be a packaging issue, but I haven't been able to replicate it locally (and it's challenging because packaging instructions are not documented). Relevant issue: #1834

I've opened a PR here which makes sure source files of extensions are actually picked up and distributed with the `sdist`: https://github.com/slundberg/shap/pull/3009

**Comment by connortann** [comment]
> @desilinguist, I think this repository already has PyPI secrets (that should be enough for release) stored in the secrets setting (named PYPI_TOKEN). It is used here to publish wheels: https://github.com/slundberg/shap/blob/f77a5ae5c6fefa9a353cdd5422e05b4e565904a3/.github/workflows/build_wheels.yml#LL89C52-L89C52.
> 
> Anyway, it is good for you as a maintainer to get access as an admin at PyPI in case anything gets wrong.
> 
> Currently, the release steps are the following (it would be nice to put instructions in some wiki):
> 
> 1. Make a new tag (e.g. 0.42) and push it to this repository
> 2. Initiate the release on GitHub (through an interface on the right-hand side in the Releases section)
> 3. The latter will trigger the https://github.com/slundberg/shap/blob/master/.github/workflows/build_wheels.yml action to make and publish wheels on PyPI.
> 
> Before the release, we should run this action to see what wheels it builds. I can try to to this later.

Small update: I believe the version number is sourced from `shap/__init__.py` rather from the git tag, so we should increment it there. Down the line we could consider single-sourcing the version number from version control (git tags).

**Comment by bmreiniger** [comment]
Maybe consider a test run to PyPI with a [release candidate](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#pre-release-versioning) version?  (I don't know a lot about it, so grain of salt. But I think that could minimize third party package impacts while testing out the release process, and the release itself by anybody interested in fetching it?)

**Comment by dsgibbons** [comment]
A release candidate could be good. Would this avoid needing to use the PyPI test server?

**Comment by connortann** [comment]
Another thought - as well as PyPi, when making a release we should consider the process of packaging to conda-forge.

**Comment by desilinguist** [comment]
@connortann FYI: https://github.com/conda-forge/shap-feedstock

**Comment by dsgibbons** [comment]
I've pinged @slundberg regarding Test PyPI secrets.

**Comment by zhimin-z** [comment]
When does the latest version be released?
I really hope for an incremental release since there are many warnings hanging around in the current distribution.

**Comment by connortann** [comment]
We've made good progress on the items above (e.g. fixing the build on Windows & Mac), so I hope we can publish release out in the next week or so.

**Comment by connortann** [comment]
We're close to publishing our next release to PyPi. Our test release to TestPyPi went smoothly and the build was passing reliably on all platforms.

However, as of this morning we're encountering a new failing build, likely due to a change in our 3rd party depencies, which is currently blocking our release. Issue tracked on #3063. Hoping to get this resolved imminently.

**Comment by thatlittleboy** [comment]
@connortann Ah.. Do you have any idea why this problem only popped up as an error during the final build? And as a warning during all of our previous tests?

**Comment by connortann** [comment]
@thatlittleboy see #3063  - I believe it's due to Tensorflow 2.13.0 (which was released 14 hours ago). This bumped the numpy version installed on our CI, with a breaking change to ragged arrays.

Should be addressed by #3064, if you'd kindly give a review

**Comment by thatlittleboy** [comment]
@connortann what unfortunate timing :x 

I've just approved and merged, if you can trigger the build sometime later today when you're free, that would be great. Thanks alot for the help!

**Comment by connortann** [comment]
Done! Release `0.42.0` is now up on PyPi  🎉 

A big thank you to everyone who contributed, this was a great community effort.

**Comment by thatlittleboy** [comment]
<img alt="zuckerberg-nice-job-team" src="https://media.giphy.com/media/JO7BToe2BmwVgWZ8gs/giphy.gif" width="270" height="480">

**Comment by connortann** [comment]
I've uploaded to conda-forge, so that's everything on the critical path complete.
