### ISSUE TITLE
DOCS: Add a Contributing guide and GH templates

### ISSUE THREAD

**Issue by connortann** [shap/shap#2980]
## Context

We can provide some helpful information to prospective contributors. This would help in a number of areas:

- Document any design choices (e.g. code style, testing requirements)
- Improve the quality of bug reports, e.g. including reproducible examples
- Improve the quality of PRs, to reduce the number of required changes in code review
- Encourage people to get involved

## TODO

The repo has a [Community Standards](https://github.com/slundberg/shap/community) page that lists a number of suggested items that repos should include:

- [ ] Add CONTRIBUTING.md : #2996
   - [ ] Setting up a local environment
   - [ ] Linting / precommit setup
   - [ ] Running tests locally
   - [ ] How to get involved as a maintainer
- [x] Add Issues Template : #2981
- [x] Add PR Template
