### ISSUE TITLE
[Meta-issue] Notebooks are outdated / non-runnable

### ISSUE THREAD

**Issue by thatlittleboy** [shap/shap#3036]
## Background

We should also make sure that our documentation is kept up to date.

A scour through the open issues in this repo and also on [StackOverflow](https://stackoverflow.com/questions/tagged/shap) shows that the outdated documentation (or lackthereof) is causing confusion among our users.

Just some examples: 
- https://github.com/slundberg/shap/issues/2786
- https://stackoverflow.com/q/76522186

---

## Plan

The plan here is to thoroughly go through each and every notebook example that we have, to:

- Run the notebook from top-to-bottom and ensure there are no errors.
- Update the prose where necessary to provide better clarity and fix any typos
- Update the code (where necessary and appropriate) to demonstrate up-to-date API & python features, such as:
  - Replacing the deprecated boston dataset
  - Using the `Explanation` API for plotting (e.g. `shap.plots.beeswarm` rather than `shap.summary_plot`)

An example of such a PR: [#3037](https://github.com/slundberg/shap/pull/3037)

## Useful info for contributors

To potential contributors (thank you in advance!), please stick to one notebook per PR when contributing.  
Also, any help in updating the GPU-related notebooks would be very much appreciated.  

We have two linting checks for notebooks, each of which has an "exclude list" that ignores notebooks that haven't been cleaned. When a notebook has been fixed up, it should be **removed from the "exclude" list** in these places:
  - The `run_notebooks_timeout` job in `scripts/run_notebooks_timeouts.py`
  - The `nbcheckorder` job in `.pre-commit-config.yaml`

For more details on how to preview the built documentation, see the [contributing guide](https://shap.readthedocs.io/en/latest/contributing.html#documentation).

## TODO

- notebooks
    - text_examples
        - language_modelling
            - [x] Language Modeling Explanation Demo.ipynb (#3691)
        - text_generation
            - [x] Open Ended GPT2 Text Generation Explanations.ipynb
        - question_answering
            - [x] Explaining a Question Answering Transformers Model.ipynb
        - translation
            - [ ] Machine Translation Explanations.ipynb
        - summarization
            - [ ] Abstractive Summarization Explanation Demo.ipynb
        - text_entailment
            - [ ] Textual Entailment Explanation Demo.ipynb
        - sentiment_analysis
            - [ ] Using custom functions and tokenizers.ipynb
            - [ ] Emotion classification multiclass example.ipynb
            - [ ] Positive vs. Negative Sentiment Classification.ipynb
            - [ ] Keras LSTM for IMDB Sentiment Classification.ipynb
    - image_examples
        - image_captioning
            - [ ] Image Captioning using Azure Cognitive Services.ipynb
            - [ ] Image Captioning using Open Source.ipynb
        - image_classification
            - [ ] Explain ResNet50 using the Partition explainer.ipynb
            - [x] PyTorch Deep Explainer MNIST example.ipynb (#3591)
            - [ ] Explain MobilenetV2 using the Partition explainer (PyTorch).ipynb
            - [ ] Multi-class ResNet50 on ImageNet (TensorFlow)-checkpoint.ipynb
            - [x] Front Page DeepExplainer MNIST Example.ipynb (#3393)
            - [ ] Multi-class ResNet50 on ImageNet (TensorFlow).ipynb
            - [ ] Multi-input Gradient Explainer MNIST Example.ipynb
            - [ ] Explain an Intermediate Layer of VGG16 on ImageNet (PyTorch).ipynb
            - [ ] Image Multi Class.ipynb
            - [ ] Explain an Intermediate Layer of VGG16 on ImageNet.ipynb
    - benchmarks
        - tabular
            - [x] Tabular Prediction Benchmark Demo.ipynb (#3338)
            - [x] Benchmark XGBoost explanations.ipynb (#3339)
        - others
            - [ ] Benchmark Debug Mode.ipynb
        - image
            - [ ] Image Multiclass Classification Benchmark Demo.ipynb
        - text
            - [ ] Machine Translation Benchmark Demo.ipynb
            - [ ] Abstractive Summarization Benchmark Demo.ipynb
            - [ ] Text Emotion Multiclass Classification Benchmark Demo.ipynb
    - overviews
        - [ ] Explaining quantitative measures of fairness.ipynb
        - [x] Be careful when interpreting predictive models in search of causal insights.ipynb
        - [ ] An introduction to explainable AI with Shapley values.ipynb
    - genomic_examples
        - [x] DeepExplainer Genomics Example.ipynb (#3458)
    - api_examples
        - maskers
            - [ ] custom.ipynb
        - explainers
            - [ ] Permutation.ipynb
            - [ ] Exact.ipynb
            - [ ] GPUTree.ipynb
        - plots
            - [ ] text.ipynb
            - [ ] decision_plot.ipynb
            - [x] scatter.ipynb #3752
            - [ ] waterfall.ipynb
            - [ ] beeswarm.ipynb
            - [ ] violin.ipynb
            - [ ] image.ipynb
            - [x] bar.ipynb  #3523
            - [ ] heatmap.ipynb
    - tabular_examples
        - model_agnostic
            - [ ] Squashing Effect.ipynb
            - [ ] Census income classification with scikit-learn.ipynb
            - [ ] Simple Kernel SHAP.ipynb
            - [ ] Multioutput Regression SHAP.ipynb
            - [x] Iris classification with scikit-learn.ipynb
            - [ ] Diabetes regression.ipynb
            - [x] Simple ~~Boston~~ California Demo.ipynb (#3332)
        - tree_based_models
            - [x] League of Legends Win Prediction with XGBoost.ipynb (#3275)
            - [x] Understanding Tree SHAP for Simple Models.ipynb (#3278, #3749)
            - [x] Census income classification with XGBoost.ipynb
            - [x] Example of loading a custom tree model into SHAP.ipynb (#3304)
            - [x] Census income classification with LightGBM.ipynb (#3303)
            - [ ] Perfomance Comparison.ipynb
            - [x] NHANES I Survival Model.ipynb (#3395)
            - [x] Python Version of Tree SHAP.ipynb (#3335)
            - [x] Catboost tutorial.ipynb (#3214)
            - [x] Scatter Density vs. Violin Plot Comparison.ipynb (#3396)
            - [x] Explaining a simple OR function.ipynb (#3037)
            - [x] Basic SHAP Interaction Value Example in XGBoost.ipynb (#3346)
            - [x] Force Plot Colors.ipynb (#3336)
            - [ ] Fitting a Linear Simulation with XGBoost.ipynb
            - [x] Front page example (XGBoost).ipynb (#3337)
            - [ ] Explaining the Loss of a Model.ipynb
        - neural_networks
            - [ ] Census income classification with Keras.ipynb
        - linear_models
            - [x] Sentiment Analysis with Logistic Regression.ipynb (#3127)
            - [x] Explaining a model that uses standardized features.ipynb (#3112)
            - [ ] Math behind LinearExplainer with correlation feature perturbation.ipynb

**Comment by connortann** [comment]
This is a great endeavour! It might be helpful to add the guidelines for notebooks (e.g. linters, style etc) in the contributing guide, perhaps under a general section about "things in need of attention"

**Comment by connortann** [comment]
Another idea which could support this endeavour could be to make use of some more Sphinx features to make the notebooks a bit more navigable, for example the **Gallery** view. There's a guide here:

https://docs.readthedocs.io/en/stable/guides/jupyter.html

**Comment by franktoffel** [comment]
+1 as I was trying to read the docs and many images were missing

**Comment by connortann** [comment]
@thatlittleboy I noticed that we seem to have two separate sets of notebooks used for documentation:

- The `/docs/notebooks` directory of `.ipynb` notebooks are hosted on ReadTheDocs
- The `/notebooks` directory of `html` pages is hosted at `shap.github.io`, for example [here](https://shap.github.io/shap/notebooks/tree_explainer/Census%20income%20classification%20with%20LightGBM.html). Theses are referenced in the Readme for example.

Shall we aim to remove this duplication, putting everything in one place in one format?

**Comment by znacer** [comment]
Hi,
I tried to update a few notebooks, but I am stuck with an error from pre-commit check (`Import block is un-sorted or un-formatted`). I tried to fix it by re arranging imports but it didn't work. I would be glad if one could help on this (#3250).

**Comment by connortann** [comment]
> Hi, I tried to update a few notebooks, but I am stuck with an error from pre-commit check (`Import block is un-sorted or un-formatted`). I tried to fix it by re arranging imports but it didn't work. I would be glad if one could help on this (#3250).

Have you installed pre-commit in your working environment? Have a look in the contributing guide for more detailed steps, and let us know if anything isn't clear.

Your specific issue seems to be because some files have not been auto-formatted correctly. You should be able to fix your issue by running:

```
pre-commit run all-files
```

Then, commit and push your changes as usual.

Nb. alternatively, you can run the ruff linter directly on a notebook with:

```
ruff check path/to/notebook.ipynb
```

Note that you need the latest ruff version installed to lint `.ipynb` files.

**Comment by znacer** [comment]
Thanks ! Managed to use `ruff check notebook.ipynb --fix` to correct the problem.

**Comment by thatlittleboy** [comment]
> @thatlittleboy I noticed that we seem to have two separate sets of notebooks used for documentation:
> 
>     * The `/docs/notebooks` directory of `.ipynb` notebooks are hosted on ReadTheDocs
> 
>     * The `/notebooks` directory of `html` pages is hosted at `shap.github.io`, for example [here](https://shap.github.io/shap/notebooks/tree_explainer/Census%20income%20classification%20with%20LightGBM.html). Theses are referenced in the Readme for example.
> 
> 
> Shall we aim to remove this duplication, putting everything in one place in one format?

@connortann Sorry I missed this, yea seems like a good idea. Let's leave it as a to-do.

**Comment by Jason-gsy** [comment]
Hope that Image Multiclass Classification Benchmark Demo.ipynb can be fixed soon. OVO

**Comment by fomightez** [comment]
Maybe I missed it, but I would add along these lines that since you have a 'launch binder' badge it would be nice if you could update things so that the session launches directly into a notebook that actually runs. You can craft your launch URL so that it will at least feature a particular notebook that will run just fine to completion in that MyBinder-served session.   
You can add a `binder` (or even `.binder`) directory so that you can add configuration files there that only the MyBinder launches will see & use. This way you can customize the environment to at least run the 'binder demo' notebook.

Backing this up, I note that someone already sort of asked for something like this five years ago in [this issue posting](https://github.com/shap/shap/issues/1598#issue-745969143).   
Informatively, I was able to fork this repo and get that requested notebook working in [the `mybinder_support` branch of my fork here](https://github.com/fomightez/shap/tree/mybinder_support) by making changes outlined above. If you click on the '`launch binder`' badge in that branch & fork you'll see it launch directly into that notebook and you can then do '`Run`' > '`Run All Cells`'. Or more simply [click here](https://mybinder.org/v2/gh/fomightez/shap/27b17a15b72c668c248b8cd968caf5d41077457f?urlpath=%2Fdoc%2Ftree%2Fnotebooks%2Fapi_examples%2Fplots%2Fwaterfall.ipynb) to launch directly.

**Comment by Jayant-kernel** [comment]
@thatlittleboy @connortann 
Hi, I’d like to work on this issue.

I’ll start by reproducing the problem, analyze the root cause, and propose a fix with appropriate tests to ensure it doesn’t regress.

Please let me know

**Comment by kronzter** [comment]
Hi maintainers,
I would like to modernize
``` Abstractive Summarization Explanation Demo.ipynb```

*posting because I saw some comments regarding explaining plans before putting up PRs.

How I plan to update: deprecations, warnings, other logic

Will update comment as I find more things.
Added to #4331 

Please advise me if I am doing something incorrectly.
Regards.

**Comment by JRV7903** [comment]
Hi @thatlittleboy ! 
I’d like to work on the Iris classification with scikit-learn notebook.
My plan is to run the notebook end-to-end, fix any execution issues, and update it to use the modern SHAP API. I’ll also clean up any outdated code patterns and improve clarity where needed.
I’ll open a PR with the fixes once everything runs cleanly. Please let me know if you have anything specific in mind.

**Comment by bhrigushi** [comment]
Hi! I've fixed the Iris classification with scikit-learn notebook as part of ESoC 2026. PR #4324, replaced deprecated shap.force_plot() with shap.plots.force() and verified it runs top to bottom without errors."

**Comment by kronzter** [comment]
Hi, would appreciate comments and feedback on #4331 as I am not sure if my approach will match the intended direction for this issue.

**Comment by Favourj-bit** [comment]
Hi @thatlittleboy @connortann 

I would like to work on updating the `Diabetes_regression.ipynb` notebook.

My plan is to migrate it from the legacy SHAP API to the current Explanation-based API, and ensure the notebook runs end-to-end with the latest version. 

This contribution is part of my ESoC application. I’ll open a PR once the updates are complete. Please let me know if you have anything else I would need to take note of.

**Comment by Soumya080** [comment]
Hi, I'd like to work on this issue. I'll start by identifying broken notebooks and fixing them step by step.

**Comment by bhrigushi** [comment]
Also fixed the Explaining the Loss of a Model notebook in PR #4325 added a beeswarm visualization and updated the outdated description.

**Comment by suhaan-24** [comment]
Hi, I'd like to work on `tabular_examples/model_agnostic/Squashing Effect.ipynb`. I'll run it end-to-end, fix any deprecated API usage, and clean up prose where needed. Will submit a PR once it's ready!

**Comment by suhaan-24** [comment]
Hey, I've fixed `Squashing Effect.ipynb` — updated to the modern `shap.Explainer` API, fixed execution ordering, and removed it from the `nbcheckorder` exclude list. PR is up here: #4357

**Comment by Soumya080** [comment]
I’ve submitted a PR (#4361) fixing issues in decision_plot.ipynb related to current dependency compatibility. Would appreciate feedback.

**Comment by EeshaHasini** [comment]
Hi, I would like to work on updating the Simple Kernel SHAP.ipynb notebook. I will ensure it runs end-to-end and update any deprecated SHAP API usage if needed.

**Comment by Favourj-bit** [comment]
Opened a PR for the `Diabetes_regression.ipynb` notebook: [#4380](https://github.com/shap/shap/pull/4380)

**Comment by suhaan-24** [comment]
Hey, I'd like to work on `Multioutput Regression SHAP.ipynb` — will fix any deprecated API calls, make sure it runs cleanly end-to-end, and remove it from the exclusion lists.

**Comment by 24f3004086** [comment]
Hi! I’d like to take up the "Positive vs. Negative Sentiment Classification.ipynb" notebook.
I’ll ensure it runs without errors, improve the documentation, and update any outdated code where necessary.

- #4397

**Comment by afrakh** [comment]
hii. i would like to work on the notebook of PyTorch Deep Explainer MNIST example.ipynb. I'll submit the PR soon

**Comment by Favourj-bit** [comment]
Opened a PR for the `Census_income_classification_with_scikit-learn.ipynb` notebook: https://github.com/shap/shap/pull/4632

**Comment by 24f3004086** [comment]
#Opened a PR for the _Explain MobilenetV2 using the Partition explainer (PyTorch).ipynb_ 
- #4643

**Comment by junaed1031** [comment]
Hi, I would like to contribute to this issue. I can start by fixing a small notebook or documentation part. Please let me know if that works.

**Comment by paras28-05** [comment]
"I'd like to work on tabular_examples/model_agnostic/Simple Kernel SHAP.ipynb"

**Comment by apoorvadarsh-hue** [comment]
Hi! I'd like to work on `tabular_examples/model_agnostic/Iris classification with scikit-learn.ipynb`. 
I'll run it end-to-end, fix any deprecated API calls, update the prose, and remove it from the exclusion lists. Will open a PR by April 22.

**Comment by paras28-05** [comment]
I'd like to work on notebooks/tabular_examples/neural_networks/Census income classification with Keras.ipynb

**Comment by ojuschugh1** [comment]
Hi team, I have opened pr for this  `Math behind LinearExplainer with correlation feature perturbation.ipynb` https://github.com/shap/shap/pull/4692

**Comment by avi-exe16** [comment]
Hi, I'd like to work on tabular_examples/model_agnostic/Multioutput Regression SHAP.ipynb. 
I'll run it end-to-end, fix any deprecated API calls, update the prose, and open a PR soon.

**Comment by gouravgangwardev** [comment]
I will work on updating notebooks/api_examples/plots/heatmap.ipynb and open a PR soon.

**Comment by gouravgangwardev** [comment]
Hi, I’d like to work on the following notebooks:

- notebooks/api_examples/plots/bar.ipynb
- notebooks/api_examples/plots/violin.ipynb
- notebooks/api_examples/plots/scatter.ipynb

For each notebook, I will:
- Run it end-to-end and ensure there are no errors
- Update deprecated API usage to the modern shap.Explainer + shap.plots interface
- Improve explanations and structure for clarity
- Ensure reproducibility where applicable
- Remove the notebooks from the exclude lists after fixing

I will submit one PR per notebook as recommended.

**Comment by Favourj-bit** [comment]
I worked on `Explaining_the_Loss_of_a_Model.ipynb` notebook as part of this issue. https://github.com/shap/shap/pull/4756

However, I have two questions please:

1. The original notebook used `feature_perturbation="independent"` which is no longer a valid 
option in the current SHAP version. I updated it to `"interventional"` as it seemed the closest 
match, but wanted to confirm this is the right choice for the log-loss use case.

2. The original notebook had a placeholder: "This notebook will be fleshed out once we post a 
full write-up of this method." Is there a write-up available now that we can link to or expand 
from? Happy to flesh out the notebook further if there is more material to work with.

**Comment by Rahuldrabit** [comment]
I want to work on model_agnostic notebook

**Comment by ojuschugh1** [comment]
@CloseChoice  it looks this issue got mistakenly closed due the github algo as whenever pr with commit message includes  `fixes #XXXX`  get merged it automatically closes that whole issue as well.

**Comment by VarshiniGunti** [comment]
Hi, I've opened a PR to modernize the Census income classification with Keras notebook as part of this effort.
PR: #[[#4913 ]](https://github.com/shap/shap/pull/4913)
Changes included: updated SHAP API calls to modern Explanation object interface, updated Keras/TensorFlow imports, fixed deprecation warnings, notebook runs end-to-end with zero errors, and removed from allow_to_fail in run_notebooks_timeouts.py.

**Comment by Dotify71** [comment]
Hello! I am participating in the European Summer of Code and would love to help update the `Simple Kernel SHAP.ipynb` notebook. I noticed it's still using the legacy `explainer.shap_values(x)` method. I have updated the notebook locally to use the modern `Explanation` API by calling the explainer directly as a callable (`explainer(x)`), and verified that it runs top-to-bottom without deprecation warnings. I'd be happy to open a PR for this!

**Comment by Rohitstwt** [comment]
Hi! I'd like to work on `tabular_examples/tree_based_models/Perfomance Comparison.ipynb`. I'll run it end-to-end, fix any deprecated API calls, update to the modern `shap.Explainer` interface, and remove it from the exclusion lists. Will open a PR shortly.

**Comment by Dotify71** [comment]
Hi @thatlittleboy, I've submitted PR #4945 which, in addition to refactoring the API, modernizes the decision_plot notebook to use the latest SHAP conventions. This should help with the effort to keep the documentation examples up-to-date.

**Comment by Aditya-acesun** [comment]
Hi, I'd like to work on fixing the tabular_examples/tree_based_models/Diabetes regression.ipynb notebook. I'll run it top to bottom, fix any errors, and update it to use the latest SHAP Explanation API.

**Comment by nikkivirtuoso** [comment]
Hi! @thatlittleboy  I'd like to work on this issue.

I investigated the problem in the Machine Translation Explanations notebook (English → Spanish / Marian tokenizer) and found that the failure occurs because Text.token_segments() assumes return_offsets_mapping=True always returns an offset_mapping key. Some SentencePiece/Marian tokenizers don't provide this key, causing a KeyError instead of falling back to the existing token-based segmentation logic.

I have a minimal fix and am also preparing a regression test. I'll open a PR shortly. If possible, could this issue be assigned to me?

**Comment by itsnevu** [comment]
Hi, I'd like to help chip away at this. I'll grab one of the notebooks that doesn't have a linked PR yet, run it end-to-end, fix errors and update it to the current API, following the one-notebook-per-PR guideline. Will comment here with which one I'm starting on.
