### ISSUE TITLE
MAINT: Improve unit test execution speed

### ISSUE THREAD

**Issue by connortann** [shap/shap#3045]
Port of https://github.com/dsgibbons/shap/issues/42

Unit tests currently take ~20 mins to complete. If we could reduce that it could help reduce the time it takes to validate PRs, improving our effectiveness as reviewers.

The pytest logs show the names of the lowest 20 tests, which is a good way to prioritise tests to improve. 

## TODO

- [x] Find a suitable smaller translation model for tests. See #3286
- [ ] (Ongoing) refactor the slowest tests to run faster
- [x] Cache the installation of the dependencies, which currently take several minutes from each test job.
- [x] Investigate parallelising the tests to run on multiple CPUs.
  - WIP attempt abandoned as it seems to actually make the tests run even slower!
- [x] Get CodeCov working, to help us evaluate relevant test coverage when reviewing PRs.

**Comment by connortann** [comment]
After #3286 , we have unfortunately lost the ~5min speedup of our test suite. I'm keen to investigate a suitable replacement translation model that we can use in the unit tests.

A few ideas come to mind:
1. We could pick an existing model from HuggingFace, looking for one with a small file size
2. We could train a small model from scratch as a fixture, including all required code in this repo
3. We could publish a dedicated model to HuggingFace that is specifically designed for lightweight testing.

I currently favour option 3, as training a translation model requires potentially a fair bit of code that is largely irrelevant to shap.
