### ISSUE TITLE
MAINT: address all deprecation warnings in test suite

### ISSUE THREAD

**Issue by connortann** [shap/shap#3066]
# Context

At present, there are several deprecation warnings in the test suite logs. If left unaddressed, these will turn into future failures.

We've had  two a few cases of breaking issues, which were previously deprecation warnings. For example, a breaking change in numpy 0.24 delayed our most recent release. Let's fix these issues whilst they're still just warnings!

As an aside, it will also be useful to explicitly ignore warnings that are not within our control or that are false positives. That will keep the pytest output concise, and mean we're more likely to spot any new important warnings. This can be done by adding a line to the `filterwarnings` setting in `pyproject.toml`.

### Where are the warnings?

Look at the most [recent test run on the master branch](https://github.com/shap/shap/actions/workflows/run_tests.yml?query=branch%3Amaster), on the job called `ubuntu-latest, 3.12, test`. Example screenshot:

<details>

![Image](https://github.com/user-attachments/assets/8066e0a5-4513-4648-90f2-63914feccea3)

</details>

## TODO

- [x] #3969
- [ ] #3970
- [x] #3971
- [ ] #3972
- [ ] #3973
- [x] #3974
- [x] #3975

## Completed

<details>

- [x] typing.io
- [x] distutils
- [x] sentencepiece
- [x] tf.keras
- [x] xgboost
- [x] LightGBM 
- [x] sklearn (column names)
- [x] Unable to determine axes for colorbar
- [x] default value of `n_init`
- [x] Numba types scheduled for deprecation
- [x] pytorch Using a non-full backward hook
- [x] Pyspark check_additivity
- [x] No data for colormapping

</details>

**Comment by znacer** [comment]
Hi,
While looking for the first sklearn task (```X has feature names, but LinearRegression was fitted without feature names```), I noticed that this warning is due to the function ```convert_to_model``` in ```shap/utils/_legacy.py```.  
The features names are removed to avoid another sklearn warning (```X does not have valid feature names, but <model> was fitted with feature names```).
I can suggest filter this specific warning as it is an intended behavior.

**Comment by connortann** [comment]
I was wondering about that one. I think the warning might be an indication that there is a risk of indexing errors.

In general a model's `predict` method may have different behaviour when passed a DataFrame rather than a numpy array, for example if it uses column names to index features (e.g. with [ColumnTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html) ). So, if a given `model` was fitted with feature names, then perhaps the feature names always need to be passed to `model.predict`?

**Comment by znacer** [comment]
This seems to have already be discussed in : #2966   
To avoid the warning about not having valid feature names, features name have been removed from the given model.
I think it is safer keeping those feature names and have a warning when the input has no feature names. In this case, I can submit a PR to modify `convert_model` function.

**Comment by SPDA36** [comment]
Hello,
I ran into this issue when trying to install `shap-0.42.1`.  `numpy` was downgraded from `1.25.2-py311h0b4df5a_0 --> 1.24.4-py311h0b4df5a_0
`. After the downgrade, I installed `shap` but then `numba `dependency issue requires further downgrade of `numpy`.  This leads to even further issues with other environment dependencies.

<details>

```
---> 23 import shap # Effective XGBoost page 152
     24 shap.initjs()

File ~\miniconda3\envs\\Lib\site-packages\shap\__init__.py:5
      1 # flake8: noqa
      3 __version__ = "0.42.1"
----> 5 from ._explanation import Explanation, Cohorts
      7 # explainers
      8 from .explainers._explainer import Explainer

File ~\miniconda3\envs\\Lib\site-packages\shap\_explanation.py:13
     10 import sklearn
     11 from slicer import Alias, Obj, Slicer
---> 13 from .utils._exceptions import DimensionError
     14 from .utils._general import OpChain
     16 # slicer confuses pylint...
     17 # pylint: disable=no-member

File ~\miniconda3\envs\\Lib\site-packages\shap\utils\__init__.py:1
----> 1 from ._clustering import (
      2     delta_minimization_order,
      3     hclust,
      4     hclust_ordering,
      5     partition_tree,
      6     partition_tree_shuffle,
      7 )
      8 from ._general import (
      9     OpChain,
     10     approximate_interactions,
   (...)
     20     suppress_stderr,
     21 )
     22 from ._masked_model import MaskedModel, make_masks

File ~\miniconda3\envs\\Lib\site-packages\shap\utils\_clustering.py:7
      5 import scipy.spatial
      6 import sklearn
----> 7 from numba import njit
      9 from ._general import safe_isinstance
     10 from ._show_progress import show_progress

File ~\miniconda3\envs\\Lib\site-packages\numba\__init__.py:55
     50             msg = ("Numba requires SciPy version 1.0 or greater. Got SciPy "
     51                    f"{scipy.__version__}.")
     52             raise ImportError(msg)
---> 55 _ensure_critical_deps()
     56 # END DO NOT MOVE
     57 # ---------------------- WARNING WARNING WARNING ----------------------------
     60 from ._version import get_versions

File ~\miniconda3\envs\\Lib\site-packages\numba\__init__.py:42, in _ensure_critical_deps()
     40     raise ImportError(msg)
     41 elif numpy_version > (1, 24):
---> 42     raise ImportError("Numba needs NumPy 1.24 or less")
     43 try:
     44     import scipy

ImportError: Numba needs NumPy 1.24 or less
```

</details>

**Comment by connortann** [comment]
@SPDA36 your comment doesn't look related to this issue, which is about deprecation warnings in the test suite. Please open a new issue if you'd like help with installing shap.

If you do include a new report please provide a reproducible example, such as a particular set of commands used to create a new environment.

Side note - FYI I took the liberty of editing your comment to enclose the traceback in collapsed section.

**Comment by SPDA36** [comment]
@connortann Thanks for the clarity and my mistake.  I created a new issue. #3186

**Comment by dsgibbons** [comment]
Figure layout changed should hopefully be fixed by https://github.com/shap/shap/pull/3200

**Comment by noxthot** [comment]
The pytorch part is addressed here:
https://github.com/shap/shap/pull/3259

**Comment by CloseChoice** [comment]
Here's an updated snapshot of all warnings from the [most recent passing CI run on master (Mar 3)](https://github.com/shap/shap/actions/runs/22637607574):

### SHAP code (actionable)

| Warning | Count/run | Source |
|---------|-----------|--------|
| `Conversion of an array with ndim > 0 to a scalar is deprecated` | **1,314,400** | `_coalition.py:295` — filed #4290 |
| `The NumPy global RNG was seeded by calling np.random.seed` | ~190 | `_beeswarm.py`, `_permutation.py`, `_gradient.py`, `datasets.py`, `benchmark/` |
| `__array_wrap__ must accept context and return_scalar` (NumPy 2.0) | ~12 | `_deep/deep_utils.py:14,22,24` |
| `return_all_scores is now deprecated` | ~4 | `tests/explainers/test_deep.py:260` — one-liner fix: `top_k=None` (#3974) |
| `Do not pass input_shape/input_dim to a layer` | ~10 | test code using old keras API (#3971) |
| `X does not have valid feature names but LGBM was fitted with feature names` | ~12 | test data missing feature names |
| `Attempting to set identical low and high ylims` | ~8 | `_scatter.py:379` |

### Upstream (not directly actionable, all on latest versions)

| Warning | Count/run | Package | Latest? |
|---------|-----------|---------|---------|
| `The structure of inputs doesn't match` | ~60 | keras 3.13.2 | Yes |
| `__array__ implementation doesn't accept copy keyword` | ~5 | keras 3.13.2 | Yes |
| `___pyct_anno` arbitrary keyword args (Python 3.15) | ~60 | gast 0.7.0 (via TF) | Yes |
| `torch.jit.script is deprecated` | ~5 | torch 2.10.0 | Yes |
| `builtin type SwigPyObject has no __module__` | ~18 | lightgbm 4.6.0 (swig) | Yes |
| `Buffer() is deprecated` (Node.js) | ~7 | Node.js | N/A |
| `Recommended: pip install sacremoses` | ~5 | transformers 4.53.3 | **No** — pinned `< 4.54.0`, latest is 5.3.0 |

Note: `transformers` is pinned to `< 4.54.0` since Oct 2025 due to test failures. Latest is now 5.3.0 — might be worth re-testing whether the pin can be lifted.

---
<sub>This comment was drafted with LLM assistance and reviewed by @CloseChoice before posting.</sub>

**Comment by krishnachaudhary18** [comment]
Hi @connortann! I'm interested in contributing as part of my ESOC project. I noticed the note about testing the transformers version pin (checking if we can move past < 4.54.0). I’d like to take this on. Could you please assign this to me, or let me know if anyone is already looking into it.

**Comment by CloseChoice** [comment]
> Hi [@connortann](https://github.com/connortann)! I'm interested in contributing as part of my ESOC project. I noticed the note about testing the transformers version pin (checking if we can move past < 4.54.0). I’d like to take this on. Could you please assign this to me, or let me know if anyone is already looking into it.

feel free to fix this, this would be really valuable

**Comment by shauryam2807** [comment]
Hello
Hi @connortann, I'm Shaurya an ESoC 2026 Batch 2 applicant for the SHAP C++/nanobind migration project. I'd like to contribute by fixing some of these deprecation warnings. I'll start with #3974 (return_all_scores deprecation) and submit a PR shortly

**Comment by shaivimalik** [comment]
Hello @connortann @CloseChoice, I’ve created two pull requests to resolve the `The structure of inputs doesn’t match` warning. After some digging, I spotted that the warning was originating from the `shap` code. I split the resolutions into two PRs to make them easier to review.

**Comment by SuMayaBee** [comment]
Hi @connortann, @CloseChoice, I've opened a PR to address the `np.random.seed` deprecation warnings.                                                                                                               #4608 replaces `np.random.seed()` with `np.random.default_rng(seed)` across the explainers, datasets, and benchmark files. It also removes a broken save/restore pattern where `np.random.seed()` was used to capture state but returns`None`, so the restore never worked correctly.

**Comment by afrakh** [comment]
hi @connortann let me know if i can open a PR for this and contribute to it if it hasnt been done already

**Comment by Nazia012** [comment]
Hi, I’m interested in working on the matplotlib deprecation warning issue (#3975) as a first contribution. Is this still available to work on?

**Comment by Dotify71** [comment]
Hi @connortann! I noticed that #4608 addresses the `np.random.seed` warnings in the explainers and datasets, but the `FutureWarning`s were still heavily spamming the test suite logs (specifically in `tests/plots/`).

I've just opened PR #4947 to handle the remaining warnings in the test suite. 

**Note on approach:** Rather than migrating `np.random.seed(0)` to `np.random.default_rng(0)` in the test suite, I applied module-level `pytest` warning filters. We discovered that passing an explicit `rng` object to plotting functions forces an upgrade to the `PCG64` generator, which diverges the pseudo-random streams and immediately breaks the legacy `pytest-mpl` visual baselines. Filtering the intentional warnings cleanly resolves the log spam without requiring a complete rewrite of the visual baselines. Let me know if this approach looks good to you!
