### ISSUE TITLE
[Meta issue] Patch release 0.42.1

### ISSUE THREAD

**Issue by connortann** [shap/shap#3082]
Pending:

- #3083
- #3078
- #3061

Release checklist:

- [x] Dry-run cibuildwheel & test
- [x] Bump version number
- [x] Update Changelog
- [x] Make GitHub release & tag
- [x] PyPI wheels published
- [x] Conda-forge published
   - https://github.com/conda-forge/shap-feedstock/pull/61
