### ISSUE TITLE
ENH: Add tests for Javascript package

### ISSUE THREAD

**Issue by connortann** [shap/shap#3100]
At present the `shapjs` javascript package does not have tests defined. We could define some tests, and run them on CI.

This would enable us to review PRs from Dependabot that update the javascript dependencies, as we'd be able to confirm that there are no breaking changes.

Related comment: https://github.com/shap/shap/pull/2949#issuecomment-1575354465

## TODO

- [x] Ensure `npm run build` (i.e. webpack) runs successfully
- [x] Get javascript tests to pass
- [x] Check that example plot renders as expected with jest snapshot (see [comment](https://github.com/shap/shap/pull/2974#issuecomment-1640305664) )
- [x] CI job to enforce JS checks

**Comment by connortann** [comment]
Closing now that at least a minimal JS test runs on CI.
