### ISSUE TITLE
[Meta-issue]: Update major versions of javascript dependencies

### ISSUE THREAD

**Issue by connortann** [shap/shap#3122]
The JS package dependencies are several years out of date, and we have several **security advisories** and NPM warnings about deprecated and unsupported packages.

Current versions contain breaking changes, and currently break the build. We should update the relevant packages, and then do some thorough manual testing of the new JS bundle.

### CICID prep

- [x] Get build running on CI
- [x] Add jest tests on CI
- [x] Get dependabot updates working

### Updates

- [x] Apply non-breaking minor updates to all packages
- [x] Update webpack
   - #3116 
   - [x] Fix broken `npm run dev` server
- [x] Update D3
   - #3114 
   - #3132
   - #3133
- [x] Update react
   - [x] Remove deprecated/outdated `react-tap-event-plugin`
   - [x] #3161
- [x] Update SSL provider
   - #3102  
- [x] Confirm all JS-related Security advisories are fixed

### Testing & deployment

- [x] Manual testing of all JS plots
- [x] Recreate `bundle.js` and place in python package
   - #3148
- [ ] Reset dependabot update frequency to monthly
- [ ] New release of npm package?

## Manually testing changes

To manually build and test the javascript bundle:

1. Run `npm run build` from the `javascript/` directory to build the bundle
2. Copy `javascript/build/bundle.js` into `shap/plots/resources/`
3. Create an example force plot, as below

```python
# Example plot to test
import xgboost
import shap

shap.initjs()
X,y = shap.datasets.california()
bst = xgboost.train({"learning_rate": 0.01}, xgboost.DMatrix(X, label=y), 100)
explainer = shap.TreeExplainer(bst)
shap_values = explainer.shap_values(X)
shap.force_plot(explainer.expected_value, shap_values[0:100,:], X.iloc[0:100,:])
```

Example output:

![image](https://github.com/shap/shap/assets/71127464/feec65a8-35d7-4e10-a3f0-5cc7fd13f2d2)
