### ISSUE TITLE
[Meta issue] Release 0.43.0

### ISSUE THREAD

**Issue by connortann** [shap/shap#3289]
Release checklist:

- [x] Review merged PRs and rename any unclear titles, add appropriate labels
- [x] Update releases template: #3297
- [x] Dry-run cibuildwheel & test: https://github.com/shap/shap/actions/runs/6393223240
- [x] Bump version number: #3296
- [x] Make GitHub release & tag
- [x] PyPI wheels published
- [x] Conda forge published

**Comment by thatlittleboy** [comment]
Just a reminder for ourselves to highlight that py3.7 support is deprecated in 0.43.0 in the release notes.

**Comment by thatlittleboy** [comment]
@connortann @dsgibbons I'm also thinking that we should briefly test on py3.12, now that it's released officially? Before we release shap 0.43.0. If possible, let's release a wheel for 3.12 as well?

**Comment by connortann** [comment]
We depend on numba which doesn't yet support 3.12. I think it typically takes a few months for numba to support a new python version, so I don't think this should hold up our `0.43.0` release.

I created an issue so we don't forget: #3305

Let's keep a close eye on numba's progress over at https://github.com/numba/numba/issues/9197

**Comment by connortann** [comment]
On a related note, following our decision in #3057 to adopt the NEP 29 convention for python support, we are now due to drop support for python 3.8.

This would be consistent with the wider ecosystem: numpy & scipy require 3.9+ on their main branch, and scikit learn is due to do the same on the next major release.

Shall we include a mention of this in the release notes? I was thinking something like:

> Following the [NEP 29 deprecation policy](https://numpy.org/neps/nep-0029-deprecation_policy.html), this will be the last major release to support python 3.8

Any objections or requests?

**Comment by connortann** [comment]
Release `0.43.0` is made and published to PyPI. I did have to re-run the `build_wheel` workflow once, as one test failed due to a HTTP timeout as can occasionally happen, but otherwise it seems to have gone smoothly so far.

I'll keep an eye on conda-forge. The conda autotick bot has [queued ](https://conda-forge.org/status/#version_updates)shap for an update to the feedstock. Edit: done.
