### ISSUE TITLE
[Meta issue] Release 0.44.0

### ISSUE THREAD

**Issue by connortann** [shap/shap#3412]
I think we are due a new release.

We haven't yet completed everything in the [0.44.0](https://github.com/shap/shap/milestone/6) milestone, but I think it would still be helpful to release what we do have.

Checklist:

- [x] Enable dynamic versioning: #3402
- [x] Dry-run cibuildwheel & test
- [x] Make GitHub release & tag
- [x] Confirm PyPI wheels published
- [x] Conda forge published

FYI @shap/shap-maintainers

**Comment by connortann** [comment]
@CloseChoice @thatlittleboy
@shap/shap-maintainers 

FYI I am planning on releasing `0.44.0` tomorrow, now that we have completed #3059. Please do let me know if you have any concerns.

**Comment by connortann** [comment]
A surprise spanner in the works. On a first attempt at publishing `v0.44.0`, the `build_wheels` workflow unexpectedly failed. The `checkout` action has a bug when fetching tags: https://github.com/actions/checkout/issues/1467

This bug only appears when the workflow itself was triggered by a tag, so it didn't show up in our testing earlier in the week when the workflow was manually triggered.

I delete the release, fixed the issue in #3425 with a workaround and re-published the release. Second time worked smoothly 🎉

**Comment by connortann** [comment]
Conda release done, so I believe that's everything.
