### ISSUE TITLE
[Meta issue] Release 0.44.1

### ISSUE THREAD

**Issue by connortann** [shap/shap#3467]
As suggested by @CloseChoice , let's make a bugfix release for the HTML regression. I suggest aiming to make the release on Thursday.

Checklist:

- [x] Fix html() method of force_plot: #3464
- [x] Dry-run cibuildwheel & test: [build_wheels job](https://github.com/shap/shap/actions/runs/7640588168)
- [x] Make GitHub release & tag
- [x] Confirm PyPI wheels published
- [x] Follow up with #3431 and #3448
- [x] Conda forge published

FYI @shap/shap-maintainers

**Comment by CloseChoice** [comment]
If I can help you with anything here, feel free to ping me and tell me which part you want to get rid of ;)

**Comment by connortann** [comment]
Thanks! This should be straightforward, not least because we've recently put a lot of effort into getting the release cycle "commit-less": for example, the version number from git tags, the release notes from GitHub PRs, and so on. 

I'll plan to make this release myself, but for the purposes of knowledge transfer feel free to look through the contributing guide to get a feel for the steps required.

**Comment by CloseChoice** [comment]
@connortann hmm, do we need to merge https://github.com/shap/shap/pull/3518 into the release? Or how can we get this into conda forge? I rerun the CI but think I missed that this #3518 is not included in the 0.44.1 tag. Or maybe it's best if we just close this here and then go straight to 0.45.0 on conda?

**Comment by connortann** [comment]
Once a release has been made, it is generally much more preferable to create new patch releases rather than overwrite a previous one. So, we could theoretically make a new branch from `0.44.1`, add fixes, and release `0.44.2`.

However- as I understand, we might be able to fix the conda-forge CI by changing the _conda_ dependencies - i.e., to specify a constraint in recipe.yaml to skip pytorch tests on macos:

https://github.com/conda-forge/shap-feedstock/blob/6d80fedb3126d20c221bee28fe96000f199101c8/recipe/meta.yaml#L66

**Comment by connortann** [comment]
Hurrah, we (finally) got the conda package deployed for `0.44.1`, which was a rather rocky process:
https://github.com/conda-forge/shap-feedstock/pull/76

Hoping the subsequent `0.45.0` will be smoother on conda-forge, now that we have dropped python 3.8 . I think we are starting to see the benefits of adopting [SPEC 0](https://scientific-python.org/specs/spec-0000/) and dropping older versions in a timely manner.

FYI @CloseChoice @DanGolding
