### ISSUE TITLE
[Meta-issue] deprecation tracker for upcoming releases

### ISSUE THREAD

**Issue by connortann** [shap/shap#3507]
This is a meta-issue to track any deprecation cycles within the shap package.

Maintainers, feel free to edit this tracker as necessary,

## Recommendations for which warning to use:

For deprecated parameters in e.g. plotting functions, we probably want `FutureWarning`.

Excerpt from [PEP0565](https://peps.python.org/pep-0565/):

> - `PendingDeprecationWarning`: hidden by default for all code. The intended audience is Python developers that take an active interest in ensuring the future compatibility of their software (e.g. professional Python application developers with specific support obligations).
> - `DeprecationWarning`: reported by default for code that runs directly in the `__main__` module (as such code is considered relatively unlikely to have a dedicated test suite), but hidden by default for code in other modules. The intended audience is Python developers that are at risk of upgrades to their dependencies (including upgrades to Python itself) breaking their software (e.g. developers using Python to script environments where someone else is in control of the timing of dependency upgrades).
> - `FutureWarning`: reported by default for all code. The intended audience is users of applications written in Python, rather than other Python developers (e.g. warning about use of a deprecated setting in a configuration file format).

## Scheduled for removal

Items that raise a DeprecationWarning due to be removed in an specific release:

### 0.45.0

- [x] #3511
- [x] #3340

Parameters which were renamed:
```
feature_dependence -> feature_perturbation
independent -> interventional
correlation -> correlation_dependent
logloss -> log_loss
margin -> raw
```

Begin raising warnings for:

- [x] Deprecate KernelExplainer.shap_values: `l1_reg="auto"` 
- [x] Deprecate Beeswarm / Violin plot `auto_size_plot`
- Covered by #3517

### 0.46.0

To be removed:

- [x] Remove Beeswarm / Violin plot `auto_size_plot`
- [x] Deprecate unused `title` parameter of `shap.plots._violin.py`
- Covered by #3717

### 0.47.0

- [x] KernelExplainer.shap_values: change default behaviour of `l1_reg` away from `"auto"` 
  - #3858
- [x] Raise warning for `shap.bar_plot`
  - #3739
- [x] Change default feature_peturbation to "auto"
  - #2624
- [x] deprecate ` approximate` in `TreeExplainer` initialisation
  - #3834

Remove unused / dead code:

- [x] `shap/utils/_masked_models.py:_build_delta_masked_inputs()`
- [x] `shap/explainers/_explainer.py:Explainer._compute_main_effects()`
  - #3856
 
### 0.48.0

To be removed:

- [ ] `shap.plots._violin.py`: remove unused `title` parameter

### 0.49.0

- [ ] Update `shap.bar_plot` to use new plotting API, delete `shap.plots._bar.bar_legacy`
- [ ] Raise error if `feature_peturbation="interventional"` and `data=None`, as per #2624
- [ ] remove ` approximate` in `TreeExplainer` initialisation, as per #3834
- [ ] KernelExplainer.shap_values: removed deprecated argument `l1_reg="auto"` 

### At some point, at our leisure

Remove unused / dead code:
- [ ] `shap/plots/_text.py:text_old()
   - We should remove this once we have overhauled the rest of `_text.py`, got the test coverage up and looked over other functions in that module e.g. `_text.saliency_plot()` and `_text.heatmap()`.

**Comment by CloseChoice** [comment]
Do we really want to deprecate `PermutationExplainer.shap_values`? That is possible for all other explainers aswell, don't see why we should introduce inconsistency here.

Edit: I would also suggest to remove `auto_size_plot` from beeswarm entirely, since it is already ignored. Maybe even something for 0.45.0?

**Comment by connortann** [comment]
> Do we really want to deprecate `PermutationExplainer.shap_values`? That is possible for all other explainers aswell, don't see why we should introduce inconsistency here.

Good point. I didn't give that one sufficient thought when I searched the repo for the word "deprecated". I'll make a PR to remove that warning.

Whilst I'm at it, I shall also ensure we have the `versionadded` and `versionchanged` notes to the docstrings of recent breaking changes.
