### ISSUE TITLE
[Meta issue] Release 0.45.0 

### ISSUE THREAD

**Issue by connortann** [shap/shap#3551]
- [x] Complete PRs in milestone:
  - #3517
  - #3549
  - #3554
- [x] Relevant deprecations
  - Tracked on #3507
- [x] Dry-run cibuildwheel & test
  - Example run https://github.com/shap/shap/actions/runs/8202163162
- [x] Make GitHub release & tag
- [x] Confirm PyPI wheels published
- [x] Conda forge published

**Comment by connortann** [comment]
@CloseChoice  FYI, once we get these last items in I think we're good to make a release!

**Comment by connortann** [comment]
@CloseChoice @DanGolding I believe we're good to make a release now, as those key PRs are in and cibuildwheel is passing. Any objections or shall I go ahead?

**Comment by CloseChoice** [comment]
No objections from my side. Let's go ahead.

**Comment by connortann** [comment]
Done 🎉 Let me know if you have any proposed edits to the release notes, in particular to the description of the breaking change to the shape of Explanation objects.

**Comment by CloseChoice** [comment]
> Done 🎉 Let me know if you have any proposed edits to the release notes, in particular to the description of the breaking change to the shape of Explanation objects.

The release notes look good to me. Let's keep it as it is. I'll put a link to the release notes on hackernews later today.
