### ISSUE TITLE
[Meta-issue] Release 0.45.1

### ISSUE THREAD

**Issue by connortann** [shap/shap#3640]
- [x] Dry-run cibuildwheel & test
  - Completed run: https://github.com/shap/shap/actions/runs/8941582973
- [x] Make GitHub release & tag
- [x] Confirm PyPI wheels published
- [x] Conda forge published

**Comment by connortann** [comment]
@CloseChoice as you suggest, shall we go ahead and make a patch release? Specifically to release #3616.

It would also help to ensure the recently completed PRs have suitable labels and titles.

**Comment by CloseChoice** [comment]
Hi connor,
I don't quite understand, isn't #3616 already released in 0.45.1? At least I see this as a milestone the issue.

**Comment by connortann** [comment]
At the time of my comment, `0.45.1` hadn't been released and I just wanted to confirm whether you were happy for the release to proceed. I went ahead and triggered it yesterday, so yep your bug fix for that issue is on PyPI now.

**Comment by CloseChoice** [comment]
perfect, totally fine with me. Sorry I didn't do much coding and maintaining the past 2 weeks so I didn't look into the shap issues. Glad that you handled that ;)

**Comment by connortann** [comment]
No problem. Apologies on my end for also being quite busy recently; I hope to get on top of some recent issues and PRs this week.
