### ISSUE TITLE
 [Meta-issue] Release 0.46.0 

### ISSUE THREAD

**Issue by CloseChoice** [shap/shap#3688]
### Problem Description

With support for tensorflow 2.16 and keras 3 I feel we can release v0.46.0 to make it available to the public.

 - [x] Update deprecation warnings according to #3507
   - #3717
 - [x] Dry-run cibuildwheel & test
   - [Example run](https://github.com/shap/shap/actions/runs/9683205842)
 - [x] Make GitHub release & tag
 - [x] Confirm PyPI wheels published
 - [x] Conda forge published

**Comment by connortann** [comment]
@CloseChoice  I agree we should make a release soon. I've update the GH milestone accordingly, to move postpone some visualisation items to `0.47.0`.

We should also ensure that the relevant deprecation warnings are sorted according to #3507.

**Comment by connortann** [comment]
@CloseChoice the wheels are up on PyPI. Let's keep an eye on https://github.com/conda-forge/shap-feedstock for the automated update PR.

**Comment by connortann** [comment]
@CloseChoice and @thatlittleboy , if you get a change it would be great to have an extra pair of eyes to help with the conda issues. In particular, the update PR on conda-forge above has not yet passed due to test failures.

I also noticed a recent issue #3765 which may be related.
